[versions]
kotlin = "2.2.20"
junit = "5.13.4"
koog = "0.4.1"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }

[libraries]
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
koog-agents = { module = "ai.koog:koog-agents", version.ref = "koog" }